---
kind: pipeline
name: default

steps:
- name: project1
  image: l.gcr.io/google/bazel:3.1.0
  depends_on: [clone]
  commands:
  - bazel test //project1/...
- name: project2
  image: l.gcr.io/google/bazel:3.1.0
  depends_on: [clone]
  commands:
  - bazel test //project2/...
- name: pyproject
  image: l.gcr.io/google/bazel:3.1.0
  depends_on: [clone]
  commands:
  - bazel test //pypackage1/...

trigger:
  event:
  - push
