---
kind: pipeline
type: kubernetes
name: default

steps:
- name: pipeline-only
  image: docker:dind
  depends_on: [clone]
  commands:
  - ls
  when:
    paths:
      include:
      - ".drone.yml"
- name: project1
  image: l.gcr.io/google/bazel:3.1.0
  depends_on: [clone]
  commands:
  - bazel test //project1/...
  when:
    paths:
      include:
      - "project1/**"
- name: project2
  image: l.gcr.io/google/bazel:3.1.0
  depends_on: [clone]
  commands:
  - bazel test //project2/...
  when:
    paths:
      include:
      - "project2/**"

trigger:
  event:
    - push

---
kind: pipeline
type: kubernetes
name: python

steps:
- name: pypackage1
  image: l.gcr.io/google/bazel:3.1.0
  depends_on: [clone]
  commands:
  - bazel test //pypackage1/...
  when:
    paths:
      include:
      - "pypackage1/**"

trigger:
  event:
    - push
