version: "1.0"
kind: pipeline
metadata:
  name: ngci-test/parallel-pipeline
  description: "Parallel pipeline"
  deprecate: {}
  project: ngci-test
spec:
  stages:
    - "test"
  triggers:
    - type: git
      provider: github
      name: path-trigger
      repo: rfblue2/ngci-test
      context: "github"
      contexts: []
      events:
        - push.heads
      branchRegex: /.*/gi
      disabled: false
      options:
        noCache: false
        noCfCache: false
        resetVolume: false
  contexts: []
  variables: []
  mode: parallel
  steps:
    project1:
      title: Project1
      type: freestyle
      image: 'l.gcr.io/google/bazel:3.1.0'
      when:
        condition:
          all:
            cloneFinish: steps.main_clone.result == 'success'
      commands:
        - bazel test //project1/...
    project2:
      title: Project1
      type: freestyle
      image: 'l.gcr.io/google/bazel:3.1.0'
      when:
        condition:
          all:
            cloneFinish: steps.main_clone.result == 'success'
      commands:
        - bazel test //project1/...
  runtimeEnvironment:
    name: arn:aws:eks:us-east-1:408272790494:cluster/ci-pub/codefresh
    cpu: 4000m
    memory: 4096Mi
    dindStorage: nullGi
