version: '1.0'
kind: pipeline
metadata:
  name: ngci-test/pipeline-creator
  description: "Pipeline creator for pipeline-spec.yml files"
  deprecate: {}
  project: ngci-test
spec:
  triggers:
    - type: git
      provider: github
      name: path-trigger
      repo: rfblue2/ngci-test
      context: "github"
      contexts: []
      events:
        - push.heads
      branchRegex: /.*/gi
      disabled: false
      options:
        noCache: false
        noCfCache: false
        resetVolume: false
  contexts: []
  variables: []
  stages:
    - 'pretest'
    - 'test'
  mode: 'parallel'
  steps:
    main_clone: # reserved name
      title: 'Cloning main repository...'
      type: git-clone
      stage: 'pretest'
      repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
      revision: '${{CF_REVISION}}'
      git: github
    create_pipelines:
      title: Setting up a new pipeline programatically
      image: codefresh/cli
      stage: 'pretest'
      when:
        steps:
          - name: main_clone
            on:
              - success
      commands:
        - ./create_pipelines.sh
    project1:
      title: "project1-test"
      type: "codefresh-run"
      stage: "test"
      arguments:
        PIPELINE_ID: ngci-test/project1
        TRIGGER_ID: path-trigger
        BRANCH: ${{CF_BRANCH}}
        VARIABLE:
          - CF_BRANCH=${{CF_BRANCH}}
          - CF_REVISION=${{CF_REVISION}}
      when:
        condition:
          all:
            cloneFinish: steps.create_pipelines.result == 'success'
            whenVarExists: 'includes("${{PROJECT1}}", "true") == true'
    project2:
      title: "project2-test"
      type: "codefresh-run"
      stage: "test"
      arguments:
        PIPELINE_ID: ngci-test/project2
        TRIGGER_ID: path-trigger
        BRANCH: ${{CF_BRANCH}}
        VARIABLE:
          - CF_BRANCH=${{CF_BRANCH}}
          - CF_REVISION=${{CF_REVISION}}
      when:
        condition:
          all:
            cloneFinish: steps.create_pipelines.result == 'success'
            whenVarExists: 'includes("${{PROJECT2}}", "true") == true'
  runtimeEnvironment:
    name: arn:aws:eks:us-east-1:408272790494:cluster/ci-pub/codefresh
    cpu: 2000m
    memory: 1024Mi
    dindStorage: nullGi
    
