# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure

pool:
  vmImage: 'ubuntu-latest'

container: l.gcr.io/google/bazel:3.1.0

steps:
- script: |
    bazel test //project1
  displayName: 'Run project1 tests'